// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaAA.Infrastructure.Data;

#nullable disable

namespace SistemaAA.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClienteProcesso", b =>
                {
                    b.Property<Guid>("ClientesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProcessosId")
                        .HasColumnType("uuid");

                    b.HasKey("ClientesId", "ProcessosId");

                    b.HasIndex("ProcessosId");

                    b.ToTable("ClienteProcesso", (string)null);
                });

            modelBuilder.Entity("ParteContrariaProcesso", b =>
                {
                    b.Property<Guid>("PartesContrariasId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProcessosId")
                        .HasColumnType("uuid");

                    b.HasKey("PartesContrariasId", "ProcessosId");

                    b.HasIndex("ProcessosId");

                    b.ToTable("ParteContrariaProcesso", (string)null);
                });

            modelBuilder.Entity("SistemaAA.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SistemaAA.Domain.Entities.ParteContraria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CnpjCpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("Setor")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PartesContrarias");
                });

            modelBuilder.Entity("SistemaAA.Domain.Entities.Processo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Admissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AdvogadoResponsavelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaptadorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataArquivamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataDeProcuracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataDeProtocolo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Demissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaseDoProcesso")
                        .HasColumnType("text");

                    b.Property<string>("MesDoMarketing")
                        .HasColumnType("text");

                    b.Property<string>("MotivoArquivamento")
                        .HasColumnType("text");

                    b.Property<string>("NumeroProcesso")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Pedidos")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("ResponsavelId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Sindicato")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TipoAcao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UF")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ValorCausa")
                        .HasColumnType("numeric");

                    b.Property<string>("VaraDoTrabalho")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdvogadoResponsavelId");

                    b.HasIndex("CaptadorId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("Processos");
                });

            modelBuilder.Entity("SistemaAA.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SupabaseAuthId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ClienteProcesso", b =>
                {
                    b.HasOne("SistemaAA.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClientesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAA.Domain.Entities.Processo", null)
                        .WithMany()
                        .HasForeignKey("ProcessosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ParteContrariaProcesso", b =>
                {
                    b.HasOne("SistemaAA.Domain.Entities.ParteContraria", null)
                        .WithMany()
                        .HasForeignKey("PartesContrariasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAA.Domain.Entities.Processo", null)
                        .WithMany()
                        .HasForeignKey("ProcessosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaAA.Domain.Entities.Processo", b =>
                {
                    b.HasOne("SistemaAA.Domain.Entities.Usuario", "AdvogadoResponsavel")
                        .WithMany()
                        .HasForeignKey("AdvogadoResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaAA.Domain.Entities.Usuario", "Captador")
                        .WithMany("ProcessosCaptados")
                        .HasForeignKey("CaptadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaAA.Domain.Entities.Usuario", "Responsavel")
                        .WithMany("ProcessosResponsaveis")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdvogadoResponsavel");

                    b.Navigation("Captador");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("SistemaAA.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("ProcessosCaptados");

                    b.Navigation("ProcessosResponsaveis");
                });
#pragma warning restore 612, 618
        }
    }
}
