server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Suporte para o Angular Router (direciona todas as rotas para index.html)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
